[STARTFILES]
StartFile01 = area := AreaProgramEdit, dialog  := SlProgramEdit, startfile := ceditor.com
StartFile02 = area := Custom, dialog  := SlEsCustomDialog, startfile := custom.com
StartFile06 = area := AreaMachine, dialog := SlMachine, menu := SlMaJogCircularGrindMenuHU, startfile := custom_jog.com ;xxx.com

;ShopTurn
; SHOPTURN Programm -> Bohren,  VSK6 "OEM Bohren"
; SHOPTURN program -> Drilling, VSK6 "Oem Drilling"
; StartFile03 = area := AreaProgramEdit, dialog  := SlProgramEdit, screen:= SlStepShopTurnDrillScreen, startfile := f_dr_o1.com

; SHOPTURN: Programm -> Verschiedenes  VSK4 "Vorrichtungen"
; SHOPTURN: Program -> Miscellaneous   VSK4 "Equipment"
; StartFile04 = area := AreaProgramEdit, dialog  := SlProgramEdit, screen:= SlStepShopTurnMiscScreen, startfile := equipmnt.com

; JOG: Manuell -> Manuell horizontaler HSK8 "Reitstock"
; JOG: Manual  -> manual horizontal    HSK8 "Tailstock"
; StartFile05 = area := AreaMachine, dialog := SlMachine, menu := SlMaJogTurnMenuHU, startfile := tail_man.com

; JOG: Manuell -> Werkzeug messen VSK5 "Messen Kante Z"
; JOG: Manual  -> Measure Tool    VSK5 "measure edge Z"
; StartFile06 = area := AreaMachine, dialog := SlMachine, screen := SlMaJogMeTurnToolRangeScreen, startfile := f_ms_o1.com


[LANGUAGEFILES]
LngFile06 = myalz.txt
;LngFile02 = alsc.txt
;LngFile03 = drilling.txt
;LngFile04 = measure.txt

[RECOMPILE_INFO_FILES]
IniFile01 = cycles1.ini
;IniFile02 = cycles2.ini

