;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Template for the configuration of area menu 
; softkeys
;
; To activate the settings remove the 
; commentary ';' at the beginning of the line
;
; To deactivate a setting use keyword <empty>:
; TextId = <empty>
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Settings for area Custom
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[Custom]
; To activate area Custom use the following setting
Visible=true
; To change the text on the area softkey use the following settings
TextId=GRINDEX
;TextFile=slam
;TextContext=SlAmAreaMenu
; To set a picture on the softkey use the following settings
;Picture=mypicture.png
; To change the position of the softkey use the following setting
SoftkeyPosition = 8

[AreaCalc]
; To activate area Custom use the following setting
Visible=true
; To change the text on the area softkey use the following settings
TextId=proba
;TextFile=slam
;TextContext=SlAmAreaMenu
; To set a picture on the softkey use the following settings
;Picture=mypicture.png
; To change the position of the softkey use the following setting
SoftkeyPosition = 11
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Template for OEM area (e.g. MyArea)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[MyArea]
; Text-ID of a language dependent text
;TextId = MY_AREA
; File name of the text file which contains the Text-ID
;TextFile = mytextfile
; Context in the text file to which the Text-ID is assigned to
;TextContext = mycontext
; File name of an icon shown on the area softkey
;Picture = mypicture.png
; Position of the area softkey on area menu, 
; If no position is specified, an empty position is searched
;SoftkeyPosition = 7
; Access level of the area softkey
;AccessLevel = 5 

